version: '3'
services:
  app:
    container_name: jekyll
    image: 'jekyll/jekyll:3'
    command: jekyll serve
    ports:
      - '4000:4000'
    volumes:
      - ./:/srv/jekyll
      - ./bundle:/usr/local/bundle
